
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
        - name: tetris
          image: san7075/boardshack # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on

